# Generated by Django 5.1.7 on 2025-03-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letter_status', models.JSONField(default=dict)),
                ('guessed_words', models.JSONField(default=list)),
                ('game_status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('correct_word', models.CharField(default='peach', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game_engine.user')),
            ],
        ),
    ]
