# Generated by Django 5.1.7 on 2025-03-23 06:30

import game_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='correct_word',
            field=models.CharField(default=game_engine.models.get_random_word, max_length=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='letter_status',
            field=models.JSONField(default=game_engine.models.all_letters),
        ),
    ]
