# Generated by Django 5.1.7 on 2025-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0002_alter_game_correct_word_alter_game_letter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
    ]
